### ISSUE TITLE
Allowing util#downloadTrack to save file with specified name.

### ISSUE THREAD

**Issue by JacobWennebro** [Tenpi/soundcloud.ts#14]
When using util#downloadTrack it forces the file to use the name of the song from Soundcloud. In my use case for example I need the file to use the id of the track rather than the song name. I think in general making an option for the file name or instead using a path maybe like so: ``songs/${id}.mp3`` would be better and more flexible.

**Comment by JacobWennebro** [comment]
Noticed that this could already be achieved with util#streamTrack, my bad.

**Comment by Tenpi** [comment]
No, don't close it it's a good suggestion.

**Comment by Tenpi** [comment]
Added in `v0.3.5`.
