### ISSUE TITLE
Unhandled promise rejection: TypeError: Soundcloud is not a constructor

### ISSUE THREAD

**Issue by Error-Cezar** [Tenpi/soundcloud.ts#21]
so i tried to use the api but when i do new Soundcloud I have `Unhandled promise rejection: TypeError: Soundcloud is not a constructor`

I used this code `   var Soundcloud = require("soundcloud.ts");
    const soundcloud = new Soundcloud();`

**Comment by Tenpi** [comment]
It's a default export, so if you are using the require import it's `const Soundcloud = require("soundcloud.ts").default`
