### ISSUE TITLE
Unhandled promise rejection: Error: Request failed with status code 403 when running search function

### ISSUE THREAD

**Issue by Error-Cezar** [Tenpi/soundcloud.ts#22]
so with whatever im trying to search it always return me `Unhandled promise rejection: Error: Request failed with status code 403`
I tried with the code in the example and I did this 
`const search = await soundcloud.tracks.search({q: "lunatic"})
      return console.log(search)`

**Comment by Tenpi** [comment]
search is deprecated. You have to use searchV2 (v2 api) or searchAlt (web scraping).

**Comment by Error-Cezar** [comment]
oh ok

**Comment by AllFatherGray** [comment]
@Moebits Sorry to necro an issue but for search is there anyway to use this to get the top 10 sings of a specific genre?
And additionally I am unable to use the sdk in the environment I am using so I must rely on http calls. For using the search in http v2 is there anything different I must do?
