### ISSUE TITLE
JSON.parse error @ playlist#getAlt & tracks#searchAlt

### ISSUE THREAD

**Issue by JeroenoBoy** [Tenpi/soundcloud.ts#25]
I am getting the following errors when using tracks#searchAlt
![image](https://user-images.githubusercontent.com/26047623/133478411-6c85c162-e699-4e67-9ef3-f30ff20245f5.png)

And this issue with playlist#getAlt
![image](https://user-images.githubusercontent.com/26047623/133478476-71f0da5b-76f8-4ef7-be0b-bf0297e2e49d.png)

**Comment by Tenpi** [comment]
Fixed as of `v0.4.2`. 

However, you should really use the better methods `getV2` and `searchV2` because the web scraping is prone to breaking.
