### ISSUE TITLE
Question: Getting a list of tracks by a specific user possible?

### ISSUE THREAD

**Issue by brentrill** [Tenpi/soundcloud.ts#35]
I'd like to get all of a users track ids, ideally with the date that it was posted. With the current API I can get the user id from the profile link, and I can get specific track ids and info from their respective track link. However, the "users/{id}/tracks" endpoint seems broken without authorization. Do you have any ideas for a workaround?

I've considered making a search query, but are we able to filter by user?

**Comment by Tenpi** [comment]
You should use:
```ts
const tracks = await soundcloud.users.tracksV2("https://soundcloud.com/username")
```
NOT `soundcloud.users.tracks`, the V1 api no longer works
