### ISSUE TITLE
Strange import result for esm module

### ISSUE THREAD

**Issue by cjh980402** [Tenpi/soundcloud.ts#39]
When I use this module in esm node.js, `SoundcloudAPI` is not class and `SoundcloudAPI.default` is class.
However, typing says `SoundcloudAPI` is class.
![image](https://user-images.githubusercontent.com/23624124/168212690-253906d0-10c0-4c98-a001-c2ce8057295e.png)

Also, in compiled js code (soundcloud.js), it has duplicated export in 50, 51 line.
```js
exports["default"] = Soundcloud;
module.exports["default"] = Soundcloud;
```

**Comment by Tenpi** [comment]
It's not a duplicated export. The first one is the es6 export, the second is for commonjs.

Are you using at least Node.js v13 >=? Earlier versions of Node required you to add the flag `--experimental-modules` and to use the `.mjs` extension to use es6 imports. Like this:

```js
node --experimental-modules app.mjs
```

**Comment by cjh980402** [comment]
I use node v16.15.0 and use `"type": "module"` in package.json of my project.

**Comment by Tenpi** [comment]
Well, just use `const soundcloud = new Soundcloud.default()` then, if you want your code to be typed you should be using Typescript and not Javascript anyways.
