### ISSUE TITLE
Not so much an issue but more a question

### ISSUE THREAD

**Issue by jimmynames** [Tenpi/soundcloud.ts#4]
I wondered if you're aware then if the soundcloud api is still 'working' 

eg, can you still trigger play on click of a custom button?
I have my own client Id and correct track id and yet in isolated enviro it's not playing.. 

Would this be possible with this package?

**Comment by Tenpi** [comment]
The soundcloud api returns error 403 for everything, so now you need to use web scraping or their undocumented v2 api. I added the method `soundcloud.util.streamLink()` which will return the direct streaming link to the track. If you use this package it will need to be on a backend server, I don't think it works in the browser.

Alternatively, [here](https://github.com/Tenpi/soundcloud-download/blob/master/index.js) is an example of how you could get the direct streaming link of a track using client-side Javascript. The main difference is that you need to send http requests through the proxy "https://cors-anywhere.herokuapp.com/" or the browser will block them.

**Comment by jimmynames** [comment]
safe for this =} mad knowledge for something that seems to be inaccessible and or abandoned so props! +1

plan on using client-side js as i've created a vr world and would love to stream music in it form soundcloud
