### ISSUE TITLE
download 320k if Go+

### ISSUE THREAD

**Issue by Vap0r1ze** [Tenpi/soundcloud.ts#45]
when using `downloadTrack` or `downloadTracks`, it should download the track at 320k if your oauth token has a Go+ subscription

**Comment by Vap0r1ze** [comment]
an easy way to fix this is probably to add an `hq` option, and to support `audio/mp4` streams into `.m4a` files

**Comment by skick1234** [comment]
Supported on `v0.5.0` (https://github.com/Tenpi/soundcloud.ts/commit/fee2a08822871f366a6f8719395560281b71cf66).
