### ISSUE TITLE
Is this for browser?

### ISSUE THREAD

**Issue by mizok** [Tenpi/soundcloud.ts#46]
I am looking for an alternative to stream tracks from SC in my website, since the original Soundcloud SDK was totally dead, I wonder if this is able to be used in browser?

**Comment by Tenpi** [comment]
If you use webpack you can import it client side. All methods except those that use Node APIs (downloading tracks, etc.) should work in the browser.

**Comment by mizok** [comment]
@Tenpi 
Thanks!  will take a try :D
